defmodule Demo.Repo.Migrations.AddCategoryToPosts do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:posts) do
      add(:category_id, :uuid)
    end

    create table(:categories, primary_key: false) do
      add(:id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true)
    end

    alter table(:posts) do
      modify(
        :category_id,
        references(:categories,
          column: :id,
          name: "posts_category_id_fkey",
          type: :uuid,
          prefix: "public"
        )
      )
    end

    alter table(:categories) do
      add(:name, :text, null: false)
      add(:description, :text)
      add(:slug, :text, null: false)

      add(:inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
      )

      add(:updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
      )
    end
  end

  def down do
    alter table(:categories) do
      remove(:updated_at)
      remove(:inserted_at)
      remove(:slug)
      remove(:description)
      remove(:name)
    end

    drop(constraint(:posts, "posts_category_id_fkey"))

    alter table(:posts) do
      modify(:category_id, :uuid)
    end

    drop(table(:categories))

    alter table(:posts) do
      remove(:category_id)
    end
  end
end
